<?php
/**
 * @file Buscador
 * @author Miguel Martínez <miguel01amd@gmail.com>
 * @package Recetario | Custom
 * @info Módulo de búsqueda para productos y recetas
 * @vertion dev 1.0.0
 */


/**
 * Implements hook_search_info().
 */
function search_search_info() {
  return array(
    'title'    => 'Recetario',
    'path'     => 'recetario-search',
  );
}

/**
 * Implements hook__search_execute().
 */
function search_search_execute($keys = NULL, $condition = NULL) {
  $results = [];
  global $base_url;

  if (!$keys) {
    $keys = '';
  }

  $qry = db_select('node', 'n');
  $qry->leftJoin('field_data_field_img_min', 'fim', 'fim.entity_id = n.nid');
  $qry->leftJoin('field_data_field_moment', 'fm', 'fm.entity_id = n.nid');
  $qry->leftJoin('field_data_field_description_ec', 'fdesc', 'fdesc.entity_id = n.nid');
  $qry->leftJoin('field_data_field_elaboracion', 'fe', 'fe.entity_id = n.nid');
  $qry->leftJoin('field_data_field_ingredients', 'fi', 'fi.entity_id = n.nid');
  $qry->leftJoin('taxonomy_term_data', 'ttd', 'ttd.tid = fm.field_moment_tid');
  $qry->leftJoin('field_data_field_icon_class', 'fic', 'fic.entity_id = ttd.tid');
  $qry->leftJoin('field_data_field_texto_informativo', 'ptx', 'ptx.entity_id = n.nid');
  $qry->leftJoin('field_data_body', 'pbody', 'pbody.entity_id = n.nid');
  $qry->leftJoin('field_data_field_ideas', 'pidea', 'pidea.entity_id = n.nid');
  $qry->condition('status', '1', '=');
  $qry->condition(db_or()
        ->condition('n.type', 'receipes', '=')
        ->condition('n.type', 'products', '='));
  $search = $qry->condition(db_or()
        ->condition('n.title', '%' . db_like($keys) . '%', 'LIKE')
        ->condition('pidea.field_ideas_value', '%' . db_like($keys) . '%', 'LIKE')
        ->condition('pbody.body_value', '%' . db_like($keys) . '%', 'LIKE')
        ->condition('ptx.field_texto_informativo_value', '%' . db_like($keys) . '%', 'LIKE')
        ->condition('fi.field_ingredients_value', '%' . db_like($keys) . '%', 'LIKE')
        ->condition('fe.field_elaboracion_value', '%' . db_like($keys) . '%', 'LIKE')
        ->condition('fdesc.field_description_ec_value', '%' . db_like($keys) . '%', 'LIKE'))
      ->fields('n', ['nid', 'title', 'type'])
      ->fields('fim', ['field_img_min_fid'])
      ->fields('fdesc', ['field_description_ec_value'])
      ->fields('ttd', ['name'])
      ->fields('fic', ['field_icon_class_value'])
      ->orderBy('n.changed', 'DESC')
      ->extend('PagerDefault')
      ->limit(10)
      ->execute();

  if (!empty($search)) {
    foreach ($search as $item) {
      $alias    = drupal_get_path_alias('node/'.$item->nid);

      $results[$item->nid] = [
        'title' => $item->title,
        'img'   => trCommon_file_path($item->field_img_min_fid),
        'desc'  => $item->field_description_ec_value,
        'link'  => $base_url.'/'.$alias,
      ];

      if ($item->type == 'receipes') {
        $results[$item->nid]['momento'] = [
          'name'  => $item->name,
          'class' => $item->field_icon_class_value,
        ];
      }//endif
    }//endforeach
  }//endif

  return $results;
}

/**
 * Implements hook_preprocess_search_result().
 */
function search_preprocess_search_result(&$variables) {
  $result = $variables['result'];

  $variables['img']     = (isset($result['img'])) ? $result['img'] : '';
  $variables['desc']    = (isset($result['desc'])) ? $result['desc'] : '';
  $variables['link']    = (isset($result['link'])) ? $result['link'] : '';
  $variables['momento'] = (isset($result['momento'])) ? $result['momento'] : '';
}
